export interface DayFact {
    id?: string; // UUID (generated by client or server)
    friendlyName: string; // e.g., "Sunday, February 9, 2026"
    dayDimension: number; // YYYYMMDD format, e.g., 20260209
    description?: string;
    meetings?: any[]; // JSON data for meetings
    tasksActive?: string[]; // Task summaries or IDs
    tasksCompleted?: string[]; // Task summaries or IDs
    notes?: string;
    timeLogs?: Record<string, any>;
    version?: number;
    deletedAt?: string;
    createdAt?: string;
    updatedAt?: string;
}

export interface MonthFact {
    id?: string; // UUID
    friendlyName: string; // e.g., "February 2026"
    monthDimension: number; // YYYYMM format, e.g., 202602
    description?: string;
    version?: number;
    deletedAt?: string;
    createdAt?: string;
    updatedAt?: string;
}
